package(
    default_visibility = ["//grok3d:__subpackages__"],
)

cc_library(
    name = "textures",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//grok3d/glad",
        "@stb",
    ],
)
