package(
    default_visibility = ["//grok3d:__subpackages__"],
)

cc_library(
    name = "glad",
    srcs = [
        "KHR/khrplatform.h",
        "glad/glad.cpp",
        "glad/glad.h",
    ],
    hdrs = [
        "glad/glad.h",
    ],
)
